services:
  postgres:
    image: postgres:16
    container_name: recepta-postgres
    env_file: ".env.local"
    environment:
      POSTGRES_DB: recepta_db
      POSTGRES_USER: recepta
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
